### ISSUE TITLE
App download failed

### ISSUE THREAD

**Issue by Kasimirsuterwinter** [holochain/launcher-tauri#64]
Neither Notebooks nor We is downloading. Both give "App download failed. Please try again later." messages. I have tried leaving the launcher app open all day and no change. 

I am running launcher on a custom built pc running Windows 10. 

Holochain Launcher v0.4.11
Holochain v0.0.143
Holochain v0.0.145
Holochain v0.0.150
Holochain v0.0.152
Holochain v0.0.154
Lair Keystore v0.2.0

**Comment by matthme** [comment]
Thanks for reporting! Unfortunately this is an issue that does not lie within the launcher itself but is a bug related to [gossiping](https://developer.holochain.org/glossary/#gossip) large files with holochain at the moment. As soon as the issue is resolved we will update the launcher accordingly to use the fixed version of holochain.

**Comment by tommycp3** [comment]
Ok good to know, I've got the same problem. :)

**Comment by matthme** [comment]
This should now be fixed (or at least significantly improved) in the latest launcher version 0.6.0. I'm letting the issue open for now because there may still be further improvement on that.

**Comment by tommycp3** [comment]
<img width="1196" alt="2022-10-11_16-09-23" src="https://user-images.githubusercontent.com/13199826/195009811-4d0a6dfa-d1f6-4c5d-9334-f6e377fb5205.png">
I just tried with the latest launcher version and still getting the same error.

**Comment by matthme** [comment]
Does the error persist if you let the launcher running in the background for a while? Gossiping of large entries is still quite slow unfortunately but if you wait and retry after a while it should work.

**Comment by matthme** [comment]
FYI: There is a new release out now that should work way better in this regard: https://github.com/holochain/launcher/releases/tag/v0.8.0

**Comment by matthme** [comment]
Closing this issue because the latest Launcher release implements the appstore/devhub pattern and downloading of apps should be smoother now.
